### ISSUE TITLE
Cocoapods seems install wrong version of player 

### ISSUE THREAD

**Issue by WingCH** [PaoloCuscela/Cards#100]
![image](https://user-images.githubusercontent.com/19588517/52535686-75690900-2d8c-11e9-9668-8b6dd06176b6.png)

**Comment by WingCH** [comment]
![image](https://user-images.githubusercontent.com/19588517/52535707-b2cd9680-2d8c-11e9-9657-0b79861a7bbd.png)

**Comment by WingCH** [comment]
i found a solution 
use ```pod 'Cards', :git => 'https://github.com/PaoloCuscela/Cards.git```

![image](https://user-images.githubusercontent.com/19588517/52543051-28fbe880-2de1-11e9-8f38-882ce31bb497.png)

**Comment by AlBehary** [comment]
Thanks, Worked for me 

> i found a solution
> use `pod 'Cards', :git => 'https://github.com/PaoloCuscela/Cards.git`
> 
> ![image](https://user-images.githubusercontent.com/19588517/52543051-28fbe880-2de1-11e9-8f38-882ce31bb497.png)

**Comment by PaoloCuscela** [comment]
Thanks, for the tip. 
Will fix in the next release
