### ISSUE TITLE
Question: How to link the card's Background Image as an outlet to access it ?

### ISSUE THREAD

**Issue by AlBehary** [PaoloCuscela/Cards#105]
Hi, I wonder If I added my card as a design for .XIB file of my UICollectionView Cell, I want to add an outlet for the background image, Text or button etc, is that possible ? and if it's not, is there a right way to add this card as a cell in collection view while still be able to dynamically change each one with code ? 

Thanks.
Hope someone respond soon, I'm really interested in the awesome card design.

**Comment by PaoloCuscela** [comment]
Nope, you can't add individual elements of a card view as an outlet, but you can add the card itself as an iboutlet and then access to the card's elements within it.
If you use customized classes for the collection view cells you can set the card in there and then change labels, images, etc whenever you want :)
