### ISSUE TITLE
Swift Compilier Error at "Demo"

### ISSUE THREAD

**Issue by thevenomsnake** [PaoloCuscela/Cards#109]
![error](https://user-images.githubusercontent.com/31892635/55333428-e645bb00-54c9-11e9-945c-1bc820253dc5.png)

Sorry to bother you, I did the 'pod install' ,and ⌘C ⌘V the 'Cards' folder to your demo project.......and I am using the latest xcode(10.2)

**Comment by PaoloCuscela** [comment]
Thanks for pointing out, 
Do you have the same issue without using 'pod install' on the demo project, too ?
And in a new project using pod install ?

To fix your problem anyway you can just remove that line.

**Comment by thevenomsnake** [comment]
without using 'pod install' on the demo project, there is still a problem. Is anything wrong with my file directory?Removing that line will bring more errors......I'm a beginner,maybe I didn't understand what you mean?

**Comment by PaoloCuscela** [comment]
The directory is fine.
What errors do you get after removing that line ?

**Comment by thevenomsnake** [comment]
and here is the video link:
https://perphet.com/file/error.mov

**Comment by PaoloCuscela** [comment]
Can you kindly list the step you made to get that error so I can try to reproduce and fix that error ?
Meanwhile if you wish to test the project on your own you can follow **[these steps.](https://github.com/PaoloCuscela/Cards#getting-started)**

**Comment by thevenomsnake** [comment]
Steps:
1.donwload the master.zip
2.unzip it
3.put the 'card' folder in the correct location
4.open the Demo.xcworkspace
5.change the 'identity' and 'signing' informations
6.click 'run' button.
7.errors came...

If I delete the 'podfile' and set a new one, errors will be like this.
![er1](https://user-images.githubusercontent.com/31892635/55455743-5f9ef400-5617-11e9-95b4-ed2872ca389b.png)


Have you seen the video I uploaded?
I have a lot of courses and may not respond to you immediately.I am sorry about this....

**Comment by snc001** [comment]
Since you're just using the demo.

Don't follow the manual copy (as noted by your step above of copying 'card' folder)

- Just unzip
- run 'pod install' at the folder called 'Demo' (you may skip this step)
- open the Demo.xcworkspace
- change the 'identity' and 'signing' informations
- click 'run' button.

that should be all good.
