### ISSUE TITLE
ShouldPresent View Controller Cycle

### ISSUE THREAD

**Issue by omarmhaimdat** [PaoloCuscela/Cards#111]
I have created a custom card, and when I open the card the ViewController works perfectly. 

The problem occurs when I open it again, it seems that it doesn't load the view properly and in fact it doesn't load at all.

I do everything programmatically.

here's a gif to reproduce the problem:

![ezgif com-optimize-3](https://user-images.githubusercontent.com/2160742/56084541-3d358380-5e2c-11e9-8ba2-4c83c0a9903a.gif)

**Comment by omarmhaimdat** [comment]
Can someone please help me with this ?

**Comment by omarmhaimdat** [comment]
Maybe I have found the problem, it seems that when I use dequeueReusableCell in my collectionView, the instance on detailVC gets deleted when the card is not on display.

But I still haven't found any solution yet.

**Comment by PaoloCuscela** [comment]
@asbis managed to solve this on issue #104 
Maybe he can help with this a little more...

**Comment by omarmhaimdat** [comment]
Thank you @PaoloCuscela it does solve the problem !
