### ISSUE TITLE
Title Layout Covers Item Title & Subtite

### ISSUE THREAD

**Issue by BailyTroyer** [PaoloCuscela/Cards#112]
Hello! 

I followed the setup demo and when I create a card from Storyboards, the view ends up looking like this: 

<img width="339" alt="Screen Shot 2019-04-14 at 10 17 04 PM" src="https://user-images.githubusercontent.com/22754190/56103952-6d038a80-5f03-11e9-9dac-adf05fb2e751.png">

All I am doing is having a card view nested within a cell, with a basic title, Item title and Item subtitle. Nothing else.

<img width="260" alt="Screen Shot 2019-04-14 at 10 17 15 PM" src="https://user-images.githubusercontent.com/22754190/56103973-8d334980-5f03-11e9-8035-239d501c919c.png">

Am I missing something when setting up the card? Or is this a potential layout bug? I'm on Xcode v10.2

**Comment by PaoloCuscela** [comment]
Nope, cards are not designed to be that large... expected aspect ratio is 5:6
