### ISSUE TITLE
CardArticle inaccessible

### ISSUE THREAD

**Issue by christoff-1992** [PaoloCuscela/Cards#12]
Hey the CardArticle is inaccessible at the moment is this intended?

`@IBDesignable class CardArticle: Card {`

**Comment by PaoloCuscela** [comment]
Nope. Fixed today in the new release.
Pod update and it will work fine :)

**Comment by christoff-1992** [comment]
👍 must have just missed it :)

**Comment by PaoloCuscela** [comment]
No problem 😉
