### ISSUE TITLE
Dismiss detailViewController on iOS 13 Simulators

### ISSUE THREAD

**Issue by Ragazzetto** [PaoloCuscela/Cards#121]
Hi Paolo 
There's a bug compiling with Xcode 11 beta and iOS 13 beta ...

The cards open correctly but when you close the detail view the screen becomes black and there is no way to do anything more 

In addition, opening the CardPlayer causes the app to crash.

`*** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<Player.Player: 0x1040b0800> should have parent view controller:<ViewController.DetailViewController: 0x103332d30> but actual parent is:<MyProject.CardsViewController: 0x103320520>'`

Thank you so much for your valuable work

Vanni

**Comment by jehumo** [comment]
This is is happening in Xcode 11 final version, only using iOS 13 simulators.
iOS 13 is unable to handle the dismissal of the detailViewController nicely.

**Comment by Ragazzetto** [comment]
In my case it is happening (with final version of Xcode 11) also on real device and not only using iOS 13 simulators.
Any idea ?

**Comment by jehumo** [comment]
I think is a genuine iOS 13 issue, this article show some tips around dismiss that  might help to mitigate the impact https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by denis-couras** [comment]
Hi, add modal presentation style equals fullScreen for DetailViewController in Card.swift for function cardTapped

**Comment by emreisik95** [comment]
> Hi, add modal presentation style equals fullScreen for DetailViewController in Card.swift for function cardTapped

It is not worked for me. It's still returns black screen both of simulator and physical devices.

**Comment by devkirios** [comment]
Hi In the function "shouldPresent" of file Card.swift add the following code:
detailVC.modalPresentationStyle = .fullScreen

With iOS 13 should force the fullscreen

regards

**Comment by devkirios** [comment]
> > Hi, add modal presentation style equals fullScreen for DetailViewController in Card.swift for function cardTapped
> 
> It is not worked for me. It's still returns black screen both of simulator and physical devices.

Hi In the function "shouldPresent" of file Card.swift add the following code:
detailVC.modalPresentationStyle = .fullScreen

With iOS 13 should force the fullscreen

regards

**Comment by Ragazzetto** [comment]
Thanks @devkirios
Finally problem solved!!!

**Comment by emreisik95** [comment]
> > > Hi, add modal presentation style equals fullScreen for DetailViewController in Card.swift for function cardTapped
> > 
> > 
> > It is not worked for me. It's still returns black screen both of simulator and physical devices.
> 
> Hi In the function "shouldPresent" of file Card.swift add the following code:
> detailVC.modalPresentationStyle = .fullScreen
> 
> With iOS 13 should force the fullscreen
> 
> regards

Thank you! You saved my app!
