### ISSUE TITLE
Action or event in button

### ISSUE THREAD

**Issue by agentelu** [PaoloCuscela/Cards#122]
HI, there is any way to add a function to the button in Card ?

**Comment by Ragazzetto** [comment]
Use the delegate method 

`func cardHighlightDidTapButton(card: CardHighlight, button: UIButton)`

For example

```
func cardHighlightDidTapButton(card: CardHighlight, button: UIButton) {        
        if card == myCard {
// add your function here
        }
    }
```

Vanni

**Comment by agentelu** [comment]
Thanks, its works

**Comment by Ragazzetto** [comment]
👍

**Comment by kevink1103** [comment]
Can anyone tell me how to do this in detail?
I am trying to use the button to do something else rather than opening detailVC.
