### ISSUE TITLE
Black screen on dismiss action iOS 13 

### ISSUE THREAD

**Issue by Pavan96** [PaoloCuscela/Cards#131]
Showing black screen on close button action on iOS 13 + iPad 10.5"

**Comment by link60** [comment]
The same on iPhone (iOS 13 simulator)

**Comment by A-M-j** [comment]
me too, I had faced this issue

**Comment by AMJ-7** [comment]
> function "shouldPresent" of file Card.swift add the following code:
> detailVC.modalPresentationStyle = .fullScreen

see more: https://github.com/PaoloCuscela/Cards/issues/121

**Comment by sashakid** [comment]
> > function "shouldPresent" of file Card.swift add the following code:
> > detailVC.modalPresentationStyle = .fullScreen
> 
> see more: #121

It doesn't work

**Comment by Pavan96** [comment]
> > function "shouldPresent" of file Card.swift add the following code:
> > detailVC.modalPresentationStyle = .fullScreen
> 
> see more: #121

@A-M-j  It worked for me I am using objective c version & tested forboth device and simulator.

**Comment by Geforceyu** [comment]
I did             detailVC.modalPresentationStyle = .fullScreen
the problem remains
Xcode 11.4.1
Project Deployment Target iOS13.0
Target Deployment iOS 13.0
Device iOS 13.3.1
