### ISSUE TITLE
Dismiss cards cause black screen on iOS13 and Xcode 11.2

### ISSUE THREAD

**Issue by Rida-ba** [PaoloCuscela/Cards#134]
First, I want to thank you for your work. It's awesome feature but
I'm sorry to let you know that it's not working anymore on iOS13 and Xcode 11.2. 
Maybe I'm the only one but I prefer to tell you.

As we can see on this following screen :

![](https://im5.ezgif.com/tmp/ezgif-5-2972857e3af1.gif)

I don't know if this is an animation issue but if you have a clue, I will be grateful.

Thanks in advance for your help.

Rida.

**Comment by Rida-ba** [comment]
Don't worry, I resolve this issue by myself. It's known problem in iOS 13 because
Apple change their view presentation style. So starting from now we have to add this following line into Cards.swift : 

detailVC.**modalPresentationStyle** = _.fullScreen_

Specially when you initialize DetailViewController in **open func initialize()**.

I hope you can fix it with my advice in the next release.

**Comment by Geforceyu** [comment]
> Don't worry, I resolve this issue by myself. It's known problem in iOS 13 because
> Apple change their view presentation style. So starting from now we have to add this following line into Cards.swift :
> 
> detailVC.**modalPresentationStyle** = _.fullScreen_
> 
> Specially when you initialize DetailViewController in **open func initialize()**.
> 
> I hope you can fix it with my advice in the next release.

Hello, after modifying according to your method, the problem remains

Xcode 11.4.1
Project Deployment Target iOS13.0
Target Deployment iOS 13.0
Device iOS 13.3.1
