### ISSUE TITLE
Presenting detail view, scrollView leaves visual artefacts.

### ISSUE THREAD

**Issue by christoff-1992** [PaoloCuscela/Cards#14]
In the detailViewController the scrollview background is set to white, however this looks a bit odd with the rounded corners of the card. Also scrolling to the bottom of the detailed view will also expose the white scrollView.

Would it be better to set this to the detailView's background colour?

`scrollView.layer.backgroundColor = UIColor.white.cgColor`

vs

`scrollView.layer.backgroundColor = detailView?.backgroundColor?.cgColor ?? UIColor.white.cgColor`

![screen shot 2017-10-30 at 09 14 16](https://user-images.githubusercontent.com/12499390/32163045-e1e7f47a-bd52-11e7-9340-bdfc20f0dcd0.png)

**Comment by PaoloCuscela** [comment]
Yep, absolutely. I'll add that in the next relase.
Thank you very much :)

**Comment by knakamura13** [comment]
It appears that this issue is back in iOS 12 (Xcode 10). I know the beta just came out this week, but is there a way I can manually change the background color behind the card so that it isn't white? Mine looks just like the screenshot above.
