### ISSUE TITLE
detailView is private variable

### ISSUE THREAD

**Issue by julius94** [PaoloCuscela/Cards#15]
Hello,

According to getting started guide 2nd step, we should do this:

```
let detailVC = storyboard?.instantiateViewController(withIdentifier: "CardContent")
card.detailView = detailVC?.view
```

But the thing is, how do you assign value to a private variable of Card class?

Here is the declaration of "detailView" property in Card class:
```
fileprivate var detailView: UIView?
```

**Comment by PaoloCuscela** [comment]
In the new release (1.2.4) detailView is set by using the method 
``swift
card.shouldPresent( _ : UIView, from _ : UIViewController)
``
I'll update the README, thanks.
