### ISSUE TITLE
Cannot update title, subtitle and category label for CardPlayer

### ISSUE THREAD

**Issue by WillChilcutt** [PaoloCuscela/Cards#16]
Hello,

Upfront I wanted to say thank your for the project!

I have a `UICollectionView` and each cell contains a `CardPlayer`. I can set the new `videoSource` and `playerCover` correctly, but in order to refresh the `CardPlayer` labels I have to call `setNeedsDisplay()` in order to get the redraw to happen. Those labels are private so I do not have access to them outside of the class.

**Comment by PaoloCuscela** [comment]
I'm fixing that right now for every card. Actually they don't update in runtime.
1.2.5 will have runtime views update and descriptions for each public attribute.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WillChilcutt** [comment]
Awesome! Thanks!
