### ISSUE TITLE
Set a button in card details

### ISSUE THREAD

**Issue by mo3bius** [PaoloCuscela/Cards#19]
Hi, I found this fantastic library. I've integrated it today, but when I try to add a button in the contents of card, it's impossible to touch.
 
Is it possible to add a button in card details?

Thank you

**Comment by PaoloCuscela** [comment]
You have to add it to your detailView. 
And then manage it in the detailView's ViewController.

If you want to add it to the card itself instead, you have to pick CardHighlight or subclass another card.

**Comment by mo3bius** [comment]
I tried to add buttons in my detailView's but the click doesn't work. Seems that the new view controller are unattainable.
If you want to see what I mean what my project (Develop branch).
https://github.com/mo3bius/My-Simple-Instagram/tree/develop

There are some buttons in in details view but if tried to click on it nothing is happening.

**Comment by PaoloCuscela** [comment]
Ok, got it. The problem was  that the detailViewController wasn't added as child of the card's presented vc.
I'll push a new release today.
Just use ``shoudPresent( :UIViewController, from :UIViewController )``
instead of ``shoudPresent( :UIView, from :UIViewController )``
