### ISSUE TITLE
Example app got crashed

### ISSUE THREAD

**Issue by victorray84** [PaoloCuscela/Cards#2]
Example app got crashed due to wrong image name used in project. "icon" name should be "Icon". Attached the screenshot
<img width="1399" alt="screen shot 2017-10-18 at 12 29 00 pm" src="https://user-images.githubusercontent.com/298531/31704813-947f715a-b400-11e7-85c6-cbfabc43d46a.png">
.

**Comment by PaoloCuscela** [comment]
Thank you very much. I'll fix it ASAP
