### ISSUE TITLE
facing internal consistency crash

### ISSUE THREAD

**Issue by pankajW** [PaoloCuscela/Cards#20]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[UIViewController _loadViewFromNibNamed:bundle:] loaded the "DetailView" nib but the view outlet was not set.'

 @objc  func cardTapped(){
        self.delegate?.cardDidTapInside?(card: self)
        
        if let vc = superVC {
            
            detailVC.detailView = detailView
            vc.present(detailVC, animated: true, completion: nil)
        } else {
            
            resetAnimated()
        }
    }

After presenting on superVC.
What could be the issue?

**Comment by PaoloCuscela** [comment]
This is probably an error on the view controller you're asking card to present. 
Can I see your project or a sample where you get it ?
