### ISSUE TITLE
Card X button

### ISSUE THREAD

**Issue by davidcl96** [PaoloCuscela/Cards#21]
Is it possible to add an X (close) button to the card, like the App Store?

**Comment by PaoloCuscela** [comment]
Yes, sure. I'm planning to add a full screen layout more similar to the iphone's appstore view, wich will include that :)

**Comment by davidcl96** [comment]
We wait for it, great work by the way.

**Comment by PaoloCuscela** [comment]
@davidcl96 New release wich implements that feature is out !
Thanks for your support ✨
