### ISSUE TITLE
A bug when using Cards in UIScrollView

### ISSUE THREAD

**Issue by big-ice** [PaoloCuscela/Cards#24]
Thanks for your great work👏!

I met an issue when I use Cards in UIScrollView. I put some cards on scrollview, and when I slide the finder with the finger holding on the card, the card call the "pushBackAnimated" method and will not call the "cardTapped" method.

**Comment by PaoloCuscela** [comment]
Thanks for the tip ! I' ll surely fix that in the next update :D

**Comment by ftitreefly** [comment]
Hi, PaloCusela, I met this issue too when I use Cards in **UIScrollView**.
I put some cards on scrollview, and when I press the card, and slide down or up **at the same time**, the card will not call 'present()' and 'resetAnimated' mothed.

**Comment by PaoloCuscela** [comment]
This happens because of the gesture recogniser that calls the touchesCancelled method.
Imo presenting the card in that case is inappropriate.
Anyway you can solve this by ovveriding ''touchesCancelled()'' method in UIGestureRecogniser extension in "Card.swift" file.
