### ISSUE TITLE
Provide access to UIImageView

### ISSUE THREAD

**Issue by ReeceHumphreys** [PaoloCuscela/Cards#26]
Would it be possible to open up access to the Card backgroundIV and iconIV in a future release to allow for easy integration with SDWebImage?

**Comment by PaoloCuscela** [comment]
If you need to access imageViews you could try subclassing Card and make a getter for private vars.
Something like this:
```swift
class MyCard: Card {

  public var backgroundImageView: UIImageView {
    get {
      return backgroundIV
    }
  }

}
```

**Comment by JEKos** [comment]
@PaoloCuscela  Doing this, it says `'backgroundIV' is inaccessible due to 'internal' protection level`

https://image.prntscr.com/image/vBhfM2wTQZeHzHu72_WnNg.png

**Comment by jordanfitnext** [comment]
I have the same error
