### ISSUE TITLE
Blur effect on Card Article content (Content settings)

### ISSUE THREAD

**Issue by WictorKihlbaum** [PaoloCuscela/Cards#29]
I am trying to set the blur effect between the background image and the title on Card Article.
I have read your Wiki regarding this and if I have understood everything right I should set the desired value on the member ’_blurEffect_’. 

However, when I try this Xcode says: _Value of type 'CardArticle' has no member ’blurEffect’_.

I can however access the other members ’_titleSize_’ and ’_subtitleSize_’ which are also mentioned under _Card Article > Content settings_ in your Wiki.

Have I misunderstood something or is this not yet implemented?

Thank you for an awesome framework and thanks in advance

**Comment by PaoloCuscela** [comment]
CardArticle has no blur effect, only Group does.
I' ve updated the wiki, thanks for the tip :)

**Comment by WictorKihlbaum** [comment]
Thanks for the clarification :) I will close this then.
