### ISSUE TITLE
Card is not showing in TableviewCell

### ISSUE THREAD

**Issue by ErAshu** [PaoloCuscela/Cards#30]
Hi PaoloCuscela,
I am facing this issue with Tableview. I have drag a view in cell and following your instructions but didn't show the card.
My code below, Please guide where i am missing things.

```
   func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 4
    }
    
```
```
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        let cardslayout = cell.viewWithTag(100) as! CardHighlight
        cardslayout.delegate = self
        let cardContent = storyboard?.instantiateViewController(withIdentifier: "CardContent")
        cardslayout.shouldPresent(cardContent, from: self, fullscreen: true)
        return cell
    }
```
![simulator screen shot - iphone 8 plus - 2017-12-08 at 21 30 26](https://user-images.githubusercontent.com/4178384/33773782-126871a8-dc5f-11e7-9e07-c2f0f9b5a9c4.png)

Thanks

**Comment by ErAshu** [comment]
@PaoloCuscela  Please help me.

**Comment by PaoloCuscela** [comment]
Could you give me an example project where you face this problem?

**Comment by ErAshu** [comment]
[TestCard.zip](https://github.com/PaoloCuscela/Cards/files/1571599/TestCard.zip)

**Comment by PaoloCuscela** [comment]
There was a problem with auto layout constrains, this is the fixed project.
[TestCard.zip](https://github.com/PaoloCuscela/Cards/files/1587111/TestCard.zip)
You should at least provide a fixed height for the card view or cell's height.
