### ISSUE TITLE
 detailview with 'uitableview' other than scrollview possible?

### ISSUE THREAD

**Issue by codejjk** [PaoloCuscela/Cards#31]
Hello, thank you so much for the great job!
Actually I want to load a uitableview in the detail screen of the Detailview.
But because the detailview is uiscrollview, 'uitableview in the scrollview' shows so weird functionality when swipe up/down.

How can I use uitableview in the detailview? just like..:
![image-1](https://user-images.githubusercontent.com/33384888/34078976-3ca3549c-e367-11e7-9b7e-79a522ec35e8.jpg)

Thanks a lot.

**Comment by PaoloCuscela** [comment]
Have you already tried to set in the detailView a non-scrollable uitableview ?

**Comment by mteera** [comment]
If you turn off the scroll how can you scroll down the taleView? It seems as though the scaled image is part of the scrollView which makes it awkward when trying to implement taleView.
