### ISSUE TITLE
Does player mode support youtube url?

### ISSUE THREAD

**Issue by Inspirelife96** [PaoloCuscela/Cards#32]
I set youtube url in player card but the shows an error "something wrong with video URL". So it doesn't support youtube shared url? any ideas to support this feature?

**Comment by PaoloCuscela** [comment]
Player card uses an SDK from Patrick Piemonte named 'Player'.
It should support every straming source as url. It's not a web view so the url should point to a video file, if the YT shared url links to a youtube page the player won't play the video in it.
