### ISSUE TITLE
Cards DetailView not showing up correctly when using with UICollectionView 

### ISSUE THREAD

**Issue by seongki1** [PaoloCuscela/Cards#38]
Hello, I am making UI just like iOS11 app store, using Cards and Detailview with UICollectionView.
I 've tried like the attached file, But..

It shows the DetailView well first a few tapping, but after loading and dismissing a few times the detailviews with swiping the collectionviewcells, the detailview does not show up correctly.
I guess indexPaths are being messed up after that. And maybe it's concerned with the dequeueReusableCell.. 

Please check my code.
Thanks a lot.
[CardDemo.zip](https://github.com/PaoloCuscela/Cards/files/1705713/CardDemo.zip)

**Comment by mteera** [comment]
I had a similar problem with the tableView too, I ran a break point and the tableView was not getting to the DataSource functions, even when I reloaded it again.

**Comment by mteera** [comment]
I have the same issue when it comes to tableViews as well :(

**Comment by PaoloCuscela** [comment]
The problem was that the card did not layout when the title label text is set.
I'll fix that in the next update.

To solve this just call "layout()" after title is set:

```swift

/**
     Text of the title label.
     */
    @IBInspectable public var title: String = "The Art of the Impossible" {
        didSet{
            titleLbl.text = title
            *** layout() ***
        }
    }

```

**Comment by seongki1** [comment]
Thank you so much for the reply.
But sadly, I think the problem does not seem to be solved yet.
The cards are okay, but the detailview does not show up correctly - not showing the label and the x button either.
<img width="373" alt="screen shot 2018-02-11 at 12 33 14 am" src="https://user-images.githubusercontent.com/9641745/36063696-86b18950-0ec3-11e8-9edf-6a7383d93511.png">
<img width="752" alt="screen shot 2018-02-11 at 12 32 22 am" src="https://user-images.githubusercontent.com/9641745/36063699-88a707b2-0ec3-11e8-9dd7-0a92ff80fdf0.png">

The former is normal, and the latter has the issue.
Thanks a lot.

**Comment by PaoloCuscela** [comment]
The x button should be hidden when the scroll view is at the top, fixed that.
It took me a bit to find out, but the problem of the label was that the card in the cell was being reused and the DetailViewController(of the card's repo) was messing everything up. 

Now a new detailVC is instantiated every time shouldPresent() is called

```swift

fileprivate var detailVC: DetailViewController!

public func shouldPresent( _ contentViewController: UIViewController?, from superVC: UIViewController?, fullscreen: Bool = false) {
        if let content = contentViewController {
            
            detailVC = DetailViewController()
            detailVC.transitioningDelegate = self
            
            self.superVC = superVC
            detailVC.addChildViewController(content)
            detailVC.detailView = content.view
            detailVC.card = self
            detailVC.delegate = self.delegate
            detailVC.isFullscreen = fullscreen
        }
    }
```

For the button just do:

```swift
xButton.alpha = 0
```
in DetailViewController's viewDidLoad()

**Comment by seongki1** [comment]
Thank you so much for the quickest fix.
It works now, like a charm!
You are So Genius😉
Have a nice weekend!

**Comment by SahilDhawan** [comment]
Card Detail View Controller not working while using FSPagerView (https://github.com/WenchaoD/FSPagerView)
