### ISSUE TITLE
iphone x bug

### ISSUE THREAD

**Issue by Ahmed-Masoud** [PaoloCuscela/Cards#39]
when any card content view is presented but in fullscreen mode part from the title is hidden under the notch !!
<img width="372" alt="screen shot 2018-02-10 at 4 12 51 pm" src="https://user-images.githubusercontent.com/14929777/36062861-4950f726-0e7d-11e8-990c-634c648f1bea.png">

**Comment by PaoloCuscela** [comment]
Thanks. Fixed that, I'll push an update this week.

**Comment by schmitzoide** [comment]
Whas this ever fixed?
