### ISSUE TITLE
Sample Code or Example

### ISSUE THREAD

**Issue by askari01** [PaoloCuscela/Cards#4]
Please Include sample code or example.

**Comment by PaoloCuscela** [comment]
Yes, sure. I'm currently working on the wiki that will include samples for every card Class :)

**Comment by PaoloCuscela** [comment]
Just added 'Getting Started' and 'Customization' pages in the Wiki.
'Delegate' coming soon.
https://github.com/PaoloCuscela/Cards/wiki.

**Comment by askari01** [comment]
few tweaks
- remove: 
- pods
- podspec file

**Comment by PaoloCuscela** [comment]
Why ?

**Comment by askari01** [comment]
podspec has your information, and its better not to commit pod files (pod install, on client machine is better) so will not have to update the demo pod files.

**Comment by PaoloCuscela** [comment]
Both podfile and podspecs are non included in the pod source files.
Only files in Cards/Sources are.

**Comment by askari01** [comment]
![Uploading Screen Shot 2017-10-23 at 5.06.48 PM.png…]()
strange, I see them.

**Comment by PaoloCuscela** [comment]
I can't see your screenshot. Can you repost it, please ?

**Comment by PaoloCuscela** [comment]
Ok, yes. It is a ref from the main folder. When installing the repo from cocoapods or manually it won't be added to your project.
