### ISSUE TITLE
How to make default header section on detailView scroll with tableView.

### ISSUE THREAD

**Issue by mteera** [PaoloCuscela/Cards#41]
I am trying to use a tableView with the detailView. But it seems as though the main image just stays static when scrolling through the tableView rather than scrolling with it. TableView works fine but I am wondering if you could make it so the main image be a part of the tableView rather than separate.

**Comment by PaoloCuscela** [comment]
I don't get the point... are you trying to add a TV  in your detailVC ?
If so keep in mind that the view of your VC is embedded in a scroll view. 
You could try making your tableView non-scrollable, so the gesture recognizer active would be the card's scrollView one.

**Comment by mteera** [comment]
Thank you for your response. I have attempted to prevent scrolling, however it seems as though the scrollView limits how much the scroll can be. So if my TV has 100 cells it can only display the first few and then you can't scroll down any further. Is there a fixed height for the detailView?

**Comment by PaoloCuscela** [comment]
yes, the detailView ( the view managed by your VC ) is fixed to a certain size in the screen but inside that you can do whatever you want. 
If you upload an example project I can help you better :)

**Comment by mteera** [comment]
Here is the sample project. I've disabled the scroll o the DetailView. But this limits the amount of scroll.
[CardTest.zip](https://github.com/PaoloCuscela/Cards/files/1908192/CardTest.zip). I simply want it to be able to scroll through multiple sections the same way the App Store works.

**Comment by PaoloCuscela** [comment]
Thanks for the example project, see #52
