### ISSUE TITLE
CardHighlight crashes on dismiss (swipe down)

### ISSUE THREAD

**Issue by eytanschulman** [PaoloCuscela/Cards#42]
I have added CardHighlight to a UICollectionViewCell, to have a few CardHighlights and be able to swipe to see more (vertically.)

I am getting this crash on dismissing it.

```
*** Assertion failure in -[UICollectionView _addScrollViewScrollObserver:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.34.4/UIScrollView.m:7995
2018-03-06 19:15:33.016450+0200 IEA[803:261955] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ERROR: UIScrollView does not support multiple observers implementing _scrollViewWillEndDraggingWithVelocity:targetContentOffset:'
```
If there isn't a reasonable solution to this issue, is there another logical way to have multiple (up to 10) CardHighlights, created dynamically in code?

Thanks

**Comment by PaoloCuscela** [comment]
Can you attach an example project ?

**Comment by PaoloCuscela** [comment]
I'm closing this. Reopen if you encounter this problem again.
