### ISSUE TITLE
Questions about cards

### ISSUE THREAD

**Issue by AaronLatnok** [PaoloCuscela/Cards#46]
Hi Paolo,
I have three questions for you.
**1.** Is it possible to hide the "VIEW" button on the card in this release of Cards?
**2.** Is it possibile show the card content inside a frame with each corner rounded (not just the upper corners)?
**3.** Is it possible hide the X button inside the card content view? Is there the possibility to add a custom way to dismiss the card content? 
Thanks

**Comment by PaoloCuscela** [comment]
1. Actually you can't, but in the next release you can hide it setting the button text to nil
2-3 No but you can edit the DetailViewController class

**Comment by PaoloCuscela** [comment]
Reopen if you need help 👍

**Comment by AaronLatnok** [comment]
Thanks for the answer. I have a problem with the button: if I set: `card.buttonText = nil` xCode says that "nil cannot be assigned to type String".
Where I'm wrong?

**Comment by MasonD3V** [comment]
"but in the next release you can hide it setting the button text to nil"

We'll have to wait for the next upcoming update.

**Comment by AaronLatnok** [comment]
My mistake, I thought that this feature was included in the last update that Paolo publish a day ago

**Comment by MasonD3V** [comment]
Ahh, sorry about that.

I had to manually hide the button inside the code.
Take this code and put it in the CardHighlight.swift like this:
```swift
actionBtn.isHidden = true
```
But now it doesn't seem to work. I'll get back to you if I find a workaround.
