### ISSUE TITLE
Rotation & Stack Views

### ISSUE THREAD

**Issue by MasonD3V** [PaoloCuscela/Cards#47]
Let me start with the rotation issue. If you were to rotate your viewcontroller on your device the card won't update, it gets worse after opening the card on a rotation. Doing so will resize the whole app and make it unusable.

Then with stack views. Setting a stack views alignment to center causes the cards to completely disappear. Odd, isn't it?

**Comment by PaoloCuscela** [comment]
I' ve fixed the orientation issue, could you be more specific about the 2nd issue ? 
Maybe posting an example project ?
Thanks

**Comment by MasonD3V** [comment]
I'm currently waiting for 1.3.2 to be downloadable through cocoapods but for now let me try to explain the stack view issue since I don't have time to make an example project.

So lets say you put two cards in one stack view, then put them in another stack view. Setting their alignment both to "Center" results in them not showing up in the app itself, but they show up in the storyboard.

Could this be a bug?

**Comment by PaoloCuscela** [comment]
I'm not so used to stack views. I usually don't use them in ios projects so its pretty difficult for me to get your point without a context.

**Comment by walterkyo** [comment]
Hi @PaoloCuscela. Thank you for the work! My current job requires this card feature and I have found that the rotation issue still occurs in 1.3.2 Demo project. As you have mentioned you fixed the issue so is that included in 1.3.2 or in coming release version? By the way, as its related to my current job, so I am currently fixing this issue and I can share so far what I did to you.

**Comment by JUJUNJIE** [comment]
![screenrecording_07-25-2018 15-11-01](https://user-images.githubusercontent.com/31103611/43185100-7b0674c2-901d-11e8-8185-cdc0bf8b61aa.gif)
How to fix the problem of card and tabbar?

**Comment by PaoloCuscela** [comment]
Orientation issues should have been fixed, see #56
