### ISSUE TITLE
[Question] Print statement in DetailViewController.swift

### ISSUE THREAD

**Issue by robinvvinod** [PaoloCuscela/Cards#48]
Hi,

Is there any particular reason you are calling `print(scrollView.frame)` in DetailViewController.swift? Using the cards in full screen causes the debugger console to be flooded with the print statements.

Thank you!

P.S Thanks for all the work you do the project, it's amazing :)

**Comment by PaoloCuscela** [comment]
Not really it's just a debug leftover. 
I' ll remove that in the next release, thanks for the tip :)
