### ISSUE TITLE
Using Cards in a CollectionView

### ISSUE THREAD

**Issue by semih-akbas** [PaoloCuscela/Cards#49]
Hi Paolo, 

First of all thanks for such a great work you've done. I'm considering using the cards in a collection view or tableview. How would you recommend to go on? I mean with the current implementation if I set the class of my CollectionViewCell main UIView to i.e. CardsHighlight and tap on one of the cells the Cards grow inside the Cell region, I want it to grow within the entire screen.

Thanks in advance,
Semih

**Comment by PaoloCuscela** [comment]
I' ve done some testing right now with a TableView and seems to be allright. 
Could you upload an example project where you face that issue ?

**Comment by zacadams01** [comment]
I believe semih-akbas is talking about how CardHighlight when tapped fills up the entirety of the screen with the X button but when every other Card is tapped they show the content squeezed with a blurred background. I might be reading it wrong but thats the problem I'm facing. Is there any easy way to switch the likes of CardPlayer to fill the entire screen like CardHighlight. I can provide screenshots if need be. :)

**Comment by zacadams01** [comment]
Actually don't worry, I've just figured my own issue. I changed `tableViewCell.cardView.shouldPresent(cardContent, from: self)` to `tableViewCell.cardView.shouldPresent(cardContent, from: self, fullscreen: true)`. Hope this answers the question.

**Comment by PaoloCuscela** [comment]
Great to know you've solved :D 
closing on this.
