### ISSUE TITLE
TableView Issues 

### ISSUE THREAD

**Issue by asikand-view** [PaoloCuscela/Cards#53]
I have cards working as TableViewCell's and they are working fine apart from two major issues.

1) When you dismiss the card, and it returns to its place in the TableView it is often misaligned or has adjusted its size strangely. 

**Notice the third cell**
![misaligned](https://user-images.githubusercontent.com/29871578/41251046-9f5ddc7a-6d6d-11e8-990d-7a55f783057f.png)

2) After opening and dismissing Cards in the TableView, eventually, the cards stop presenting the view controller content. Like this: 

**Working**
![screen shot 2018-06-11 at 11 51 21 am](https://user-images.githubusercontent.com/29871578/41251148-ea405aa6-6d6d-11e8-8d25-5037f8536ac5.png)
**Stops Presenting**
![screen shot 2018-06-11 at 11 52 10 am](https://user-images.githubusercontent.com/29871578/41251151-eb78f428-6d6d-11e8-8325-dffebd03ce23.png)

**Comment by Varmoes** [comment]
I've got the same two issues. On issue number 1, I found it's affected by scrolling (if you put your finger on a card and start scrolling, it seems to interpret it as being long pressed).

**Comment by asikand-view** [comment]
I think we need to go in the Pod and find the long press action. I found it before it has to do with scaling the view to 90% of its size on a long press and then that messes up the constraints within the TableView.

**Comment by asikand-view** [comment]
I think the disappearing content has to do with the View becoming stale as part of a stack or there being some kind of a memory issue, I'm no pro but I think it could relate to #43

**Comment by asikand-view** [comment]
I've solved Issue Number 1 with this fix in Card.swift:

```
private func pushBackAnimated() {
    //UIView.animate(withDuration: 0.2, animations: { self.transform = CGAffineTransform(scaleX: 0.95, y: 0.95) })
}
```

**Comment by PaoloCuscela** [comment]
Fixed each of them. Good work 👍

**Comment by skeetyeet** [comment]
Hi I am still getting the 2nd issue. How was it solved in this case? Thanks in advance.
