### ISSUE TITLE
Centering Title Label

### ISSUE THREAD

**Issue by asikand-view** [PaoloCuscela/Cards#54]
So I'm trying to center the Title Label for a particular view I'm building. I managed to center the Category Label by setting

`categoryLbl.textAlignment = .center`

But when I try to do the same thing for titleLbl, nothing happens. This is where I am right now:

![screen shot 2018-06-11 at 12 47 03 pm](https://user-images.githubusercontent.com/29871578/41253549-933c7372-6d75-11e8-9922-f6e74fda8205.png)

**Comment by asikand-view** [comment]
I've tried playing around with the 

`categoryLbl.frame`
and
`titleLbl.frame`

but I can't seem to find a correct formula for setting the x, y, and width

**Comment by PaoloCuscela** [comment]
If you want to create a custom card you can inherit 'Card' class and use the layout method to lay your UI objects inside. You can use 'backgroundIV.bounds as a rect reference.
That method is called during the animations after changing the backgroundIV frame, so the size of your UIViews should be dependent on it.
