### ISSUE TITLE
Card animation glitch with fullscreen enabled

### ISSUE THREAD

**Issue by Nerkyator** [PaoloCuscela/Cards#57]
Hi!
I've found a little glitch in this awesome library :)

Step to reproduce:

First ViewController:
background color: _black_
card (CardHighlight) background color: _red_

Second ViewController (detailViewController):
background color: _green_

I open the card details with fullScreen option set to true

After closing, when the details is "shrinked" to card size I can see the green corners under the red rounded corners of the card for a while, then they disappears. It seems that a property animation jumps to its end without fading.

I attached 3 screenshot just to be clear :)

[Card](https://ibb.co/ea71yd)
[Detail](https://ibb.co/cmKEJd)
[Glitch](https://ibb.co/g2VbWy)

**Comment by PaoloCuscela** [comment]
Fixed. Try with the latest update ;)
