### ISSUE TITLE
Animation problem of card and tabbar

### ISSUE THREAD

**Issue by JUJUNJIE** [PaoloCuscela/Cards#58]
![screenrecording_07-25-2018 15-11-01](https://user-images.githubusercontent.com/31103611/43185222-d77ee162-901d-11e8-9341-cda25b72d8f2.gif)
How to fix the problem of card and tabbar?

**Comment by PaoloCuscela** [comment]
@walterkyo Exactly. 
You can solve this by hiding the tabbar before the animation in the Animator file so the snapshot in the animation context will be TabBar-free.
Apple anyway solves this by presenting a new tab bar in the animation context.
