### ISSUE TITLE
Add Subviews to Card View Not Possible on Xib File

### ISSUE THREAD

**Issue by muhasturk** [PaoloCuscela/Cards#65]
I would like to create custom Card View that includes some other child views inside itself. When I run project the result does not look like what I want. Subviews are not visible. 

**Subviews inside Card View**
![](https://image.ibb.co/nPd6RU/Screen_Shot_2018_08_14_at_16_10_41.png)

**Subviews Over Card View**
![](https://image.ibb.co/dsmbRU/Screen_Shot_2018_08_14_at_16_15_50.png)

Subviews over Card View looks ok, however it comes with tap gesture recognizer problem vs.

How can I properly make custom nib Card file?

**Comment by PaoloCuscela** [comment]
I don’t think you can do it by storyboard.
To make a custom Card layot the best approach would be creating a Card’ subclass and laying out your subviews in the layout(CGRect) method
