### ISSUE TITLE
Cards inside a UITableView

### ISSUE THREAD

**Issue by ITforHome** [PaoloCuscela/Cards#67]
Hi everbody,

thanks a lot for the awesome Cards. It looks great and i am very happy with that...
But i have a problem, when i using the cards inside a UITableView. It looks like this:

<img width="447" alt="cardui_issue_uitableview" src="https://user-images.githubusercontent.com/27279514/44155347-4bfefca8-a0ad-11e8-84c1-5ea8523c7cf9.png">

How can i change the shadow and the Colors, to make the Look better?
Thanks for our answer and our help

**Comment by PaoloCuscela** [comment]
You can use card’ methods to adjust shadows... take a look at the card.swift file or at the wiki 👍
