### ISSUE TITLE
Swift compiler error on 11.4

### ISSUE THREAD

**Issue by JaviOverflow** [PaoloCuscela/Cards#68]
I'm having the following error while compiling.

https://cl.ly/0O3S2H1S030A/Image%202018-08-15%20at%205.26.05%20PM.png

It's a brand new XCode project and I installed `Cards` by running `pod install` then `pod update`.

Any idea about solving this?

**Comment by Ren-Toyokawa** [comment]
I also experienced the same error.
There is a problem with the dependent Player, and by lowering the Player version to 0.8.4, the error is removed. (Perhaps the current Player version is 9.0)

Specifically, please include the following description in Podfile.

``` 
  pod 'Player', '~> 0.8.4' <
```
