### ISSUE TITLE
Card content offset in iPhoneX safezone 

### ISSUE THREAD

**Issue by federico2390** [PaoloCuscela/Cards#76]
((https://user-images.githubusercontent.com/42987961/45067342-042d7780-b0c3-11e8-99a8-21e8640f2273.gif))

hi how can I solve the problem of the superior zone when the card content show

**Comment by iTubalCain** [comment]
follow

**Comment by federico2390** [comment]
i have solved but on iPhone X I have this problem, why?
<img width="376" alt="schermata 2018-09-12 alle 02 46 21" src="https://user-images.githubusercontent.com/42987961/45395359-13b63e80-b636-11e8-9c4e-2a74d6915fd9.png">

**Comment by PaoloCuscela** [comment]
Do you still face this issue ?
If so, could you provide an example project ?
I currently can't reproduce this on iPhone X | iOS 12

**Comment by federico2390** [comment]
yes, where can I send it?

Il giorno 23 dic 2018, alle ore 15:58, Paolo Cuscela <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Do you still face this issue ?
If so, could you provide an example project ?
I currently can't reproduce this on iPhone X | iOS 12

**Comment by PaoloCuscela** [comment]
You can attach it here, or upload to an external service and share the link.

**Comment by federico2390** [comment]
Ok, I send it later.
