### ISSUE TITLE
Failed to build Objective-C 

### ISSUE THREAD

**Issue by thijsheijden** [PaoloCuscela/Cards#84]
When importing Cards it just says 'Failed to build objective-C library'. Im running the latest xcode and swift versions. Please help as I really want to use this awesome pod!

**Comment by PaoloCuscela** [comment]
Can you post a screenshot and an example project ?
Are you using cocoapods or importing manually ?

**Comment by SamuelBzn** [comment]
Worked for me : 

- Quit XCode
- Delete project's temp files located at ~/Library/Developer/Xcode/DerivedData
- Delete ProjectName.xcworkspace, Podfile.lock file and Pods folder
- Run pod install
- Open the newly created ProjectName.xcworkspace file and build

**Comment by thijsheijden** [comment]
Thanks for the help but that didn't work for me :(

**Comment by thijsheijden** [comment]
Thanks that worked! Any words on when an update to support Swift 4.2 will come?

**Comment by PaoloCuscela** [comment]
Glad you solved your issue !
Now it fully supports 4.2 :D
