### ISSUE TITLE
Does this work with swift 4.2?

### ISSUE THREAD

**Issue by rlam3** [PaoloCuscela/Cards#85]
Does this work with swift 4.2?

**Comment by rlam3** [comment]
![screen shot 2018-10-16 at 2 52 18 pm](https://user-images.githubusercontent.com/1154044/47043388-1f27e880-d153-11e8-9e0e-d08d5a9977b3.png)

I'm getting the following errors.

**Comment by PaoloCuscela** [comment]
That is a dependency from another framework.
Please refer to https://github.com/piemonte/Player
