### ISSUE TITLE
Add Card to Collection View [Question]

### ISSUE THREAD

**Issue by kraj011** [PaoloCuscela/Cards#89]
Hey so i am trying to add the card to a horizontal scrolling collection view. However, I have tried several things and none seem to work. The card at its base is just a UIView I believe but ive still had no luck implementing it as such. Any help is appreciated :D Thanks!

**Comment by PaoloCuscela** [comment]
Yes, Card is an UIView. You can use is as you would do in a tableview.
In the storyboard placing an UIView inside the prototype cell and subclassing it into Card.
Or by code instantiating it in a Custom Cell Class
