### ISSUE TITLE
Scroll view

### ISSUE THREAD

**Issue by arshia1382** [PaoloCuscela/Cards#93]
Why scroll view doesn’t work even it's enabled in viewController?
I think there is a bug

**Comment by PaoloCuscela** [comment]
Can you please provide an example project ?

**Comment by arshia1382** [comment]
Well, right now I don’t have any example project but I can’t add more that 2 cards in my iPhone view controller and adding scroll view doesn’t fix that

**Comment by PaoloCuscela** [comment]
Did you managed to solve ?

**Comment by arshia1382** [comment]
Yes, thanks. 🙏

**Comment by PaoloCuscela** [comment]
Great :D
