### ISSUE TITLE
!!! This cocopaods does not support swift 4.2. Demo is not working. 

### ISSUE THREAD

**Issue by rlam3** [PaoloCuscela/Cards#95]
Demo is not working. What version of cocoapods player is supposed to work?

Thank you.

<img width="251" alt="screen shot 2019-01-08 at 9 59 02 am" src="https://user-images.githubusercontent.com/1154044/50842325-0c751800-132c-11e9-923e-923c1651c34d.png">

**Comment by hechen** [comment]
you can just set specific swift version like this in the local .podspec.

`s.swift_version = '4.0'`

**Comment by PaoloCuscela** [comment]
#100
