### ISSUE TITLE
Value of type 'CardHighlight?' has no member 'detailView' 

### ISSUE THREAD

**Issue by bradenboothby** [PaoloCuscela/Cards#97]
Does anyone know how to fix this error?
<img width="1440" alt="screen shot 2019-01-16 at 9 24 28 pm" src="https://user-images.githubusercontent.com/37314746/51291513-61bcc380-19d5-11e9-91bc-ad18df116135.png">

**Comment by AlBehary** [comment]
Same issue here

**Comment by AlBehary** [comment]
I found a solution for that: 

first write this line: `let detailVC = storyboard?.instantiateViewController(withIdentifier: "CardContent")`

then this one instead of the detailView: `card.shouldPresent(detailVC, from: self)`

This worked for me.
Hope it helps.

**Comment by PaoloCuscela** [comment]
Al is right. detailView is a property of the ViewController managed by the Card class. 
Both are not accessible directly anyway, you should use card.shouldPresent(.class, from: self) 
to set you view controller.

**Comment by gangfang** [comment]
Hi @PaoloCuscela thanks for the awesome library!

Just a friendly suggestion here, you may update the wiki because in it `card.detailView = detailVC?.view` is still used and the content there seems not up to date.

Thanks!
