### ISSUE TITLE
Open Card Programmatically 

### ISSUE THREAD

**Issue by Ragazzetto** [PaoloCuscela/Cards#99]
Grazie Paolo per lo stupendo lavoro !!

Un informazione ...
c'è un modo per aprire la detailView di una card via codice ? 

Grazie in anticipo 

Thanks Paolo for the wonderful job!

An information ...
is there a way to open the detailView of a card via code ?

Thank you in advance

Vanni

**Comment by phr85** [comment]
It's a workaround but you can try this:
`        DispatchQueue.main.async {
            let card = self.viewWithTag(1000) as! CardGroupSliding
            card.touchesBegan(Set(arrayLiteral: UITouch()), with: UIEvent())
            card.touchesEnded(Set(arrayLiteral: UITouch()), with: UIEvent())
        }`

**Comment by Ragazzetto** [comment]
Thank you @phr85  
I'll try as soon as I can. 
Thank you so much!

Vanni

**Comment by Ragazzetto** [comment]
Yes !!
Works perfectly!
Thank you very much @phr85
